const products = [
  {
    id: 1,
    name: "Laptop",
    category: "Electronics",
    price: 1200,
    brand: "Dell",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Smartphone",
    category: "Electronics",
    price: 999,
    brand: "Apple",
    rating: 4.8,
  },
  {
    id: 3,
    name: "Headphones",
    category: "Audio",
    price: 199,
    brand: "Sony",
    rating: 4.3,
  },
  {
    id: 4,
    name: "Smartwatch",
    category: "Wearables",
    price: 350,
    brand: "Samsung",
    rating: 4.7,
  },
  {
    id: 5, 
    name: "Bluetooth Speaker",
    category: "Audio",
    price: 149,
    brand: "JBL",
    rating: 4.6,
  },
  {
    id: 6,
    name: "Tablet",
    category: "Electronics",
    price: 450,
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: 7,
    name: "Wireless Mouse",
    category: "Accessories",
    price: 25,
    brand: "Logitech",
    rating: 4.2,
  },
  {
    id: 8,
    name: "Keyboard",
    category: "Accessories",
    price: 40,
    brand: "Microsoft",
    rating: 4.1,
  },
  {
    id: 9,
    name: "Camera",
    category: "Photography",
    price: 799,
    brand: "Canon",
    rating: 4.6,
  },
  {
    id: 10,
    name: "External Hard Drive",
    category: "Storage",
    price: 90,
    brand: "Seagate",
    rating: 4.3,
  },
];

module.exports = products;
